name: CI devops 2025
on:
  push:
    branches:
      - main
      - develop
  pull_request: null
jobs:
  test-backend:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: temurin
      - name: Build and test with Maven
        run: |
          cd simple-api
          mvn clean verify